//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ITSDataModel", "BaseObjectReferences", "BaseObjectReferenceRole", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Luminis.Its.Services.Data.Impl.BaseObject), "BackReferencesRole", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Luminis.Its.Services.Data.Impl.BaseObject))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ITSDataModel", "BaseObjectValueReferences", "BaseObjectValueReferenceRole", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Luminis.Its.Services.Data.Impl.BaseObjectValue), "BackReferencesRole", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Luminis.Its.Services.Data.Impl.BaseObjectValue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ITSDataModel", "BaseObjectRelation1", "BaseObjectRelation1Role", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Luminis.Its.Services.Data.Impl.BaseObject), "BackRelations1Role", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Luminis.Its.Services.Data.Impl.BaseObject))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ITSDataModel", "BaseObjectRelation2", "BaseObjectRelation2Role", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Luminis.Its.Services.Data.Impl.BaseObject), "BackRelations2Role", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Luminis.Its.Services.Data.Impl.BaseObject))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ITSDataModel", "BaseObjectBaseObjectValues", "BaseObjectRole", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Luminis.Its.Services.Data.Impl.BaseObject), "BaseObjectValuesRole", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Luminis.Its.Services.Data.Impl.BaseObjectValue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ITSDataModel", "BaseObjectTypeBaseObject", "BaseObjectType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Luminis.Its.Services.Data.Impl.BaseObjectType), "BaseObjects", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Luminis.Its.Services.Data.Impl.BaseObject))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ITSDataModel", "FK_ObjectJournal_Object", "BaseObject", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Luminis.Its.Services.Data.Impl.BaseObject), "ObjectJournal", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Luminis.Its.Services.Data.Impl.BaseObjectJournal))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ITSDataModel", "FK_ObjectJournal_ObjectValueAfter", "BaseObjectValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Luminis.Its.Services.Data.Impl.BaseObjectValue), "ObjectJournal", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Luminis.Its.Services.Data.Impl.BaseObjectJournal))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ITSDataModel", "FK_ObjectJournal_ObjectValueBefore", "BaseObjectValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Luminis.Its.Services.Data.Impl.BaseObjectValue), "ObjectJournal", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Luminis.Its.Services.Data.Impl.BaseObjectJournal))]

// Original file name:
// Generation date: 15-4-2014 23:33:10
namespace Luminis.Its.Services.Data.Impl
{
    
    /// <summary>
    /// There are no comments for ItsDb in the schema.
    /// </summary>
    public partial class ItsDb : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ItsDb object using the connection string found in the 'ItsDb' section of the application configuration file.
        /// </summary>
        public ItsDb() : 
                base("name=ItsDb", "ItsDb")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ItsDb object.
        /// </summary>
        public ItsDb(string connectionString) : 
                base(connectionString, "ItsDb")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ItsDb object.
        /// </summary>
        public ItsDb(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ItsDb")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for BaseObjectSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<BaseObject> BaseObjectSet
        {
            get
            {
                if ((this._BaseObjectSet == null))
                {
                    this._BaseObjectSet = base.CreateQuery<BaseObject>("[BaseObjectSet]");
                }
                return this._BaseObjectSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<BaseObject> _BaseObjectSet;
        /// <summary>
        /// There are no comments for BaseObjectValueSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<BaseObjectValue> BaseObjectValueSet
        {
            get
            {
                if ((this._BaseObjectValueSet == null))
                {
                    this._BaseObjectValueSet = base.CreateQuery<BaseObjectValue>("[BaseObjectValueSet]");
                }
                return this._BaseObjectValueSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<BaseObjectValue> _BaseObjectValueSet;
        /// <summary>
        /// There are no comments for BaseObjectTypeSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<BaseObjectType> BaseObjectTypeSet
        {
            get
            {
                if ((this._BaseObjectTypeSet == null))
                {
                    this._BaseObjectTypeSet = base.CreateQuery<BaseObjectType>("[BaseObjectTypeSet]");
                }
                return this._BaseObjectTypeSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<BaseObjectType> _BaseObjectTypeSet;
        /// <summary>
        /// There are no comments for BaseObjectJournalSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<BaseObjectJournal> BaseObjectJournalSet
        {
            get
            {
                if ((this._BaseObjectJournalSet == null))
                {
                    this._BaseObjectJournalSet = base.CreateQuery<BaseObjectJournal>("[BaseObjectJournalSet]");
                }
                return this._BaseObjectJournalSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<BaseObjectJournal> _BaseObjectJournalSet;
        /// <summary>
        /// There are no comments for BaseObjectSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToBaseObjectSet(BaseObject baseObject)
        {
            base.AddObject("BaseObjectSet", baseObject);
        }
        /// <summary>
        /// There are no comments for BaseObjectValueSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToBaseObjectValueSet(BaseObjectValue baseObjectValue)
        {
            base.AddObject("BaseObjectValueSet", baseObjectValue);
        }
        /// <summary>
        /// There are no comments for BaseObjectTypeSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToBaseObjectTypeSet(BaseObjectType baseObjectType)
        {
            base.AddObject("BaseObjectTypeSet", baseObjectType);
        }
        /// <summary>
        /// There are no comments for BaseObjectJournalSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToBaseObjectJournalSet(BaseObjectJournal baseObjectJournal)
        {
            base.AddObject("BaseObjectJournalSet", baseObjectJournal);
        }
    }
    /// <summary>
    /// There are no comments for ITSDataModel.BaseObject in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ITSDataModel", Name="BaseObject")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class BaseObject : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new BaseObject object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="extId">Initial value of ExtId.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static BaseObject CreateBaseObject(global::System.Guid id, string extId)
        {
            BaseObject baseObject = new BaseObject();
            baseObject.Id = id;
            baseObject.ExtId = extId;
            return baseObject;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Guid _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(global::System.Guid value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property ExtId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ExtId
        {
            get
            {
                return this._ExtId;
            }
            set
            {
                this.OnExtIdChanging(value);
                this.ReportPropertyChanging("ExtId");
                this._ExtId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ExtId");
                this.OnExtIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ExtId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnExtIdChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnExtIdChanged();
        /// <summary>
        /// There are no comments for BackReferences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectReferences", "BackReferencesRole")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<BaseObject> BackReferences
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<BaseObject>("ITSDataModel.BaseObjectReferences", "BackReferencesRole");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<BaseObject>("ITSDataModel.BaseObjectReferences", "BackReferencesRole", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectReference in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectReferences", "BaseObjectReferenceRole")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public BaseObject BaseObjectReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectReferences", "BaseObjectReferenceRole").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectReferences", "BaseObjectReferenceRole").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectReference in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<BaseObject> BaseObjectReferenceReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectReferences", "BaseObjectReferenceRole");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<BaseObject>("ITSDataModel.BaseObjectReferences", "BaseObjectReferenceRole", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BackRelations1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectRelation1", "BackRelations1Role")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<BaseObject> BackRelations1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<BaseObject>("ITSDataModel.BaseObjectRelation1", "BackRelations1Role");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<BaseObject>("ITSDataModel.BaseObjectRelation1", "BackRelations1Role", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectRelation1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectRelation1", "BaseObjectRelation1Role")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public BaseObject BaseObjectRelation1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectRelation1", "BaseObjectRelation1Role").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectRelation1", "BaseObjectRelation1Role").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectRelation1 in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<BaseObject> BaseObjectRelation1Reference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectRelation1", "BaseObjectRelation1Role");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<BaseObject>("ITSDataModel.BaseObjectRelation1", "BaseObjectRelation1Role", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BackRelations2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectRelation2", "BackRelations2Role")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<BaseObject> BackRelations2
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<BaseObject>("ITSDataModel.BaseObjectRelation2", "BackRelations2Role");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<BaseObject>("ITSDataModel.BaseObjectRelation2", "BackRelations2Role", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectRelation2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectRelation2", "BaseObjectRelation2Role")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public BaseObject BaseObjectRelation2
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectRelation2", "BaseObjectRelation2Role").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectRelation2", "BaseObjectRelation2Role").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectRelation2 in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<BaseObject> BaseObjectRelation2Reference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectRelation2", "BaseObjectRelation2Role");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<BaseObject>("ITSDataModel.BaseObjectRelation2", "BaseObjectRelation2Role", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectValues in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectBaseObjectValues", "BaseObjectValuesRole")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<BaseObjectValue> BaseObjectValues
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<BaseObjectValue>("ITSDataModel.BaseObjectBaseObjectValues", "BaseObjectValuesRole");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<BaseObjectValue>("ITSDataModel.BaseObjectBaseObjectValues", "BaseObjectValuesRole", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectTypeBaseObject", "BaseObjectType")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public BaseObjectType BaseObjectType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectType>("ITSDataModel.BaseObjectTypeBaseObject", "BaseObjectType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectType>("ITSDataModel.BaseObjectTypeBaseObject", "BaseObjectType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<BaseObjectType> BaseObjectTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectType>("ITSDataModel.BaseObjectTypeBaseObject", "BaseObjectType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<BaseObjectType>("ITSDataModel.BaseObjectTypeBaseObject", "BaseObjectType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectJournal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "FK_ObjectJournal_Object", "ObjectJournal")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<BaseObjectJournal> BaseObjectJournal
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<BaseObjectJournal>("ITSDataModel.FK_ObjectJournal_Object", "ObjectJournal");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<BaseObjectJournal>("ITSDataModel.FK_ObjectJournal_Object", "ObjectJournal", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ITSDataModel.BaseObjectValue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ITSDataModel", Name="BaseObjectValue")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class BaseObjectValue : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new BaseObjectValue object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="endDate">Initial value of EndDate.</param>
        /// <param name="contentType">Initial value of ContentType.</param>
        /// <param name="version">Initial value of Version.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static BaseObjectValue CreateBaseObjectValue(global::System.Guid id, global::System.DateTime startDate, global::System.DateTime endDate, string contentType, int version)
        {
            BaseObjectValue baseObjectValue = new BaseObjectValue();
            baseObjectValue.Id = id;
            baseObjectValue.StartDate = startDate;
            baseObjectValue.EndDate = endDate;
            baseObjectValue.ContentType = contentType;
            baseObjectValue.Version = version;
            return baseObjectValue;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Guid _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(global::System.Guid value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property StartDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this.ReportPropertyChanging("StartDate");
                this._StartDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StartDate");
                this.OnStartDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _StartDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStartDateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for property EndDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this.ReportPropertyChanging("EndDate");
                this._EndDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EndDate");
                this.OnEndDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _EndDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEndDateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for property ContentType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ContentType
        {
            get
            {
                return this._ContentType;
            }
            set
            {
                this.OnContentTypeChanging(value);
                this.ReportPropertyChanging("ContentType");
                this._ContentType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ContentType");
                this.OnContentTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ContentType;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnContentTypeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnContentTypeChanged();
        /// <summary>
        /// There are no comments for property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte[] Content
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Content);
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte[] _Content;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnContentChanging(byte[] value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for property Version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this.ReportPropertyChanging("Version");
                this._Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Version");
                this.OnVersionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Version;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVersionChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for BackReferences in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectValueReferences", "BackReferencesRole")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<BaseObjectValue> BackReferences
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<BaseObjectValue>("ITSDataModel.BaseObjectValueReferences", "BackReferencesRole");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<BaseObjectValue>("ITSDataModel.BaseObjectValueReferences", "BackReferencesRole", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectValueReference in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectValueReferences", "BaseObjectValueReferenceRole")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public BaseObjectValue BaseObjectValueReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectValue>("ITSDataModel.BaseObjectValueReferences", "BaseObjectValueReferenceRole").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectValue>("ITSDataModel.BaseObjectValueReferences", "BaseObjectValueReferenceRole").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectValueReference in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<BaseObjectValue> BaseObjectValueReferenceReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectValue>("ITSDataModel.BaseObjectValueReferences", "BaseObjectValueReferenceRole");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<BaseObjectValue>("ITSDataModel.BaseObjectValueReferences", "BaseObjectValueReferenceRole", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ParentBaseObject in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectBaseObjectValues", "BaseObjectRole")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public BaseObject ParentBaseObject
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectBaseObjectValues", "BaseObjectRole").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectBaseObjectValues", "BaseObjectRole").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ParentBaseObject in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<BaseObject> ParentBaseObjectReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.BaseObjectBaseObjectValues", "BaseObjectRole");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<BaseObject>("ITSDataModel.BaseObjectBaseObjectValues", "BaseObjectRole", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectBeforeJournals in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "FK_ObjectJournal_ObjectValueAfter", "ObjectJournal")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<BaseObjectJournal> BaseObjectBeforeJournals
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<BaseObjectJournal>("ITSDataModel.FK_ObjectJournal_ObjectValueAfter", "ObjectJournal");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<BaseObjectJournal>("ITSDataModel.FK_ObjectJournal_ObjectValueAfter", "ObjectJournal", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectAfterJournals in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "FK_ObjectJournal_ObjectValueBefore", "ObjectJournal")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<BaseObjectJournal> BaseObjectAfterJournals
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<BaseObjectJournal>("ITSDataModel.FK_ObjectJournal_ObjectValueBefore", "ObjectJournal");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<BaseObjectJournal>("ITSDataModel.FK_ObjectJournal_ObjectValueBefore", "ObjectJournal", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ITSDataModel.BaseObjectType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ITSDataModel", Name="BaseObjectType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class BaseObjectType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new BaseObjectType object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static BaseObjectType CreateBaseObjectType(int id, string name)
        {
            BaseObjectType baseObjectType = new BaseObjectType();
            baseObjectType.Id = id;
            baseObjectType.Name = name;
            return baseObjectType;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for property RelativeUri in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string RelativeUri
        {
            get
            {
                return this._RelativeUri;
            }
            set
            {
                this.OnRelativeUriChanging(value);
                this.ReportPropertyChanging("RelativeUri");
                this._RelativeUri = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RelativeUri");
                this.OnRelativeUriChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _RelativeUri;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRelativeUriChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRelativeUriChanged();
        /// <summary>
        /// There are no comments for BaseObjects in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "BaseObjectTypeBaseObject", "BaseObjects")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<BaseObject> BaseObjects
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<BaseObject>("ITSDataModel.BaseObjectTypeBaseObject", "BaseObjects");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<BaseObject>("ITSDataModel.BaseObjectTypeBaseObject", "BaseObjects", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ITSDataModel.BaseObjectJournal in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ITSDataModel", Name="BaseObjectJournal")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class BaseObjectJournal : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new BaseObjectJournal object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="username">Initial value of Username.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static BaseObjectJournal CreateBaseObjectJournal(int id, global::System.DateTime timestamp, string username)
        {
            BaseObjectJournal baseObjectJournal = new BaseObjectJournal();
            baseObjectJournal.Id = id;
            baseObjectJournal.Timestamp = timestamp;
            baseObjectJournal.Username = username;
            return baseObjectJournal;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property Timestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this.ReportPropertyChanging("Timestamp");
                this._Timestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Timestamp");
                this.OnTimestampChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _Timestamp;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTimestampChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for property Username in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this.OnUsernameChanging(value);
                this.ReportPropertyChanging("Username");
                this._Username = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Username");
                this.OnUsernameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Username;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsernameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsernameChanged();
        /// <summary>
        /// There are no comments for BaseObject in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "FK_ObjectJournal_Object", "BaseObject")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public BaseObject BaseObject
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.FK_ObjectJournal_Object", "BaseObject").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.FK_ObjectJournal_Object", "BaseObject").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for BaseObject in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<BaseObject> BaseObjectReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObject>("ITSDataModel.FK_ObjectJournal_Object", "BaseObject");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<BaseObject>("ITSDataModel.FK_ObjectJournal_Object", "BaseObject", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectValueBefore in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "FK_ObjectJournal_ObjectValueAfter", "BaseObjectValue")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public BaseObjectValue BaseObjectValueBefore
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectValue>("ITSDataModel.FK_ObjectJournal_ObjectValueAfter", "BaseObjectValue").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectValue>("ITSDataModel.FK_ObjectJournal_ObjectValueAfter", "BaseObjectValue").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectValueBefore in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<BaseObjectValue> BaseObjectValueBeforeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectValue>("ITSDataModel.FK_ObjectJournal_ObjectValueAfter", "BaseObjectValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<BaseObjectValue>("ITSDataModel.FK_ObjectJournal_ObjectValueAfter", "BaseObjectValue", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectValueAfter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ITSDataModel", "FK_ObjectJournal_ObjectValueBefore", "BaseObjectValue")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public BaseObjectValue BaseObjectValueAfter
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectValue>("ITSDataModel.FK_ObjectJournal_ObjectValueBefore", "BaseObjectValue").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectValue>("ITSDataModel.FK_ObjectJournal_ObjectValueBefore", "BaseObjectValue").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for BaseObjectValueAfter in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<BaseObjectValue> BaseObjectValueAfterReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<BaseObjectValue>("ITSDataModel.FK_ObjectJournal_ObjectValueBefore", "BaseObjectValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<BaseObjectValue>("ITSDataModel.FK_ObjectJournal_ObjectValueBefore", "BaseObjectValue", value);
                }
            }
        }
    }
}
