//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Luminis.Its.Workbench.ClassDiagram")]

namespace Luminis.Its.Workbench
{
	/// <summary>
	/// DomainClass ClassDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("Luminis.Its.Workbench.ClassDiagram.DisplayName", typeof(global::Luminis.Its.Workbench.WorkbenchDomainModel), "Luminis.Its.Workbench.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Luminis.Its.Workbench.ClassDiagram.Description", typeof(global::Luminis.Its.Workbench.WorkbenchDomainModel), "Luminis.Its.Workbench.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("b3aa99e6-38af-404c-b4dc-e411ec7c8f0b")]
	public partial class ClassDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::Luminis.Its.Workbench.WorkbenchToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Swimlane support
		
		/// <summary>
		/// Gets whether or not swimlanes are supported in this Diagram.
		/// </summary>
		public override bool HasSwimlanes
		{
			get { return true; }
		}
		
		/// <summary>
		/// Initializes the starting swimlanes in a new Diagram.
		/// </summary>
		/// <remarks>
		/// This method is not called during successful deserialization, only when either a blank diagram is created or diagram deserialization fails and a diagram is created to make things work.
		/// 
		/// This method does not create shapes for swimlanes with shape maps specified in the DSL definition, only those swimlanes which are not mapped.
		/// The assumption here is that if a swimlane is mapped to a domain class, then an instance of that class  will be created when the element mapped to the diagram is created,
		/// and swimlane shapes will be created as part of view fixup.
		/// </remarks>
		internal virtual void InitializeSwimlanes()
		{
		}
		
		/// <summary>
		/// Gets a collection of domain classes which are mapped to swimlane shapes.
		/// </summary>
		public override sealed global::System.Collections.Generic.IEnumerable<DslModeling::DomainClassInfo> CreatableSwimLaneSubjects
		{
			get
			{
				yield return this.Store.DomainDataDirectory.GetDomainClass(typeof(global::Luminis.Its.Workbench.ObjectModelSpec));
				yield return this.Store.DomainDataDirectory.GetDomainClass(typeof(global::Luminis.Its.Workbench.CaseFileModelSpec));
			}
		}
		
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			CompartmentItemAddRule.ElementAdded(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			CompartmentItemDeleteRule.ElementDeleted(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			CompartmentItemChangeRule.ElementPropertyChanged(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, true /* repaint only */);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Most connectors are mapped to element links, but there can be exceptions. This method tell if a connector should be
		/// mapped to an element link.
		/// </summary>
		public override bool IsConnectorMappedToLink(DslDiagrams::BinaryLinkShape connector)
		{
			#region Check Parameters
			global::System.Diagnostics.Debug.Assert(connector != null);
			if (connector == null)
				throw new global::System.ArgumentNullException("connector");
			#endregion
			if (connector.GetType() == typeof(global::Luminis.Its.Workbench.CaseFileToModelConnector))
				return false;
			return base.IsConnectorMappedToLink(connector);
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::Luminis.Its.Workbench.ModelEntity)
			{
				global::Luminis.Its.Workbench.ModelEntityShape newShape = new global::Luminis.Its.Workbench.ModelEntityShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.ModelComplexType)
			{
				global::Luminis.Its.Workbench.ModelComplexTypeShape newShape = new global::Luminis.Its.Workbench.ModelComplexTypeShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.ModelRelation)
			{
				global::Luminis.Its.Workbench.ModelRelationShape newShape = new global::Luminis.Its.Workbench.ModelRelationShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.CaseFileEntity)
			{
				global::Luminis.Its.Workbench.CaseFileEntityShape newShape = new global::Luminis.Its.Workbench.CaseFileEntityShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.CaseFileRelation)
			{
				global::Luminis.Its.Workbench.CaseFileRelationShape newShape = new global::Luminis.Its.Workbench.CaseFileRelationShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.CaseFileModelSpec)
			{
				global::Luminis.Its.Workbench.CaseFileSpecLane newShape = new global::Luminis.Its.Workbench.CaseFileSpecLane(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.ObjectModelSpec)
			{
				global::Luminis.Its.Workbench.ObjectModelLane newShape = new global::Luminis.Its.Workbench.ObjectModelLane(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.Comment)
			{
				global::Luminis.Its.Workbench.CommentBoxShape newShape = new global::Luminis.Its.Workbench.CommentBoxShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.CommentReferencesSubjects)
			{
				global::Luminis.Its.Workbench.CommentConnector newShape = new global::Luminis.Its.Workbench.CommentConnector(this.Partition);
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.RelationHasEntity)
			{
				global::Luminis.Its.Workbench.RelationConnector newShape = new global::Luminis.Its.Workbench.RelationConnector(this.Partition);
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.EntityHasRelations)
			{
				global::Luminis.Its.Workbench.EntityConnector newShape = new global::Luminis.Its.Workbench.EntityConnector(this.Partition);
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.ModelTypeReferencesModelComplexTypes)
			{
				global::Luminis.Its.Workbench.ComplexTypeConnector newShape = new global::Luminis.Its.Workbench.ComplexTypeConnector(this.Partition);
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.CaseFileEntityReferencesChildCaseFileRelations)
			{
				global::Luminis.Its.Workbench.CaseFileElementConnector newShape = new global::Luminis.Its.Workbench.CaseFileElementConnector(this.Partition);
				return newShape;
			}
			if(element is global::Luminis.Its.Workbench.CaseFileRelationReferencesChildCaseFileEntity)
			{
				global::Luminis.Its.Workbench.CaseFileElementConnector newShape = new global::Luminis.Its.Workbench.CaseFileElementConnector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::Luminis.Its.Workbench.ModelEntityShape.DecoratorsInitialized += ModelEntityShapeDecoratorMap.OnDecoratorsInitialized;
			global::Luminis.Its.Workbench.CommentBoxShape.DecoratorsInitialized += CommentBoxShapeDecoratorMap.OnDecoratorsInitialized;
			global::Luminis.Its.Workbench.ObjectModelLane.DecoratorsInitialized += ObjectModelLaneDecoratorMap.OnDecoratorsInitialized;
			global::Luminis.Its.Workbench.CaseFileSpecLane.DecoratorsInitialized += CaseFileSpecLaneDecoratorMap.OnDecoratorsInitialized;
			global::Luminis.Its.Workbench.CaseFileRelationShape.DecoratorsInitialized += CaseFileRelationShapeDecoratorMap.OnDecoratorsInitialized;
			global::Luminis.Its.Workbench.CaseFileEntityShape.DecoratorsInitialized += CaseFileEntityShapeDecoratorMap.OnDecoratorsInitialized;
			global::Luminis.Its.Workbench.ModelRelationShape.DecoratorsInitialized += ModelRelationShapeDecoratorMap.OnDecoratorsInitialized;
			global::Luminis.Its.Workbench.ModelComplexTypeShape.DecoratorsInitialized += ModelComplexTypeShapeDecoratorMap.OnDecoratorsInitialized;
			global::Luminis.Its.Workbench.ComplexTypeConnector.DecoratorsInitialized += ComplexTypeConnectorDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ModelEntityShape.
		/// </summary>
		internal static partial class ModelEntityShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ModelEntityShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CommentBoxShape.
		/// </summary>
		internal static partial class CommentBoxShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CommentBoxShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.Comment.TextDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Comment").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ObjectModelLane.
		/// </summary>
		internal static partial class ObjectModelLaneDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ObjectModelLane.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Title").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CaseFileSpecLane.
		/// </summary>
		internal static partial class CaseFileSpecLaneDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CaseFileSpecLane.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Title").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CaseFileRelationShape.
		/// </summary>
		internal static partial class CaseFileRelationShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CaseFileRelationShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Title").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CaseFileEntityShape.
		/// </summary>
		internal static partial class CaseFileEntityShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CaseFileEntityShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Title").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Title").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ModelRelationShape.
		/// </summary>
		internal static partial class ModelRelationShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ModelRelationShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ModelComplexTypeShape.
		/// </summary>
		internal static partial class ModelComplexTypeShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ModelComplexTypeShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ComplexTypeConnector.
		/// </summary>
		internal static partial class ComplexTypeConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ComplexTypeConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Luminis.Its.Workbench.ModelTypeReferencesModelComplexTypes.ContainerNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		#region Connect actions
		private global::Luminis.Its.Workbench.CommentsReferenceTypesConnectAction commentsReferenceTypesConnectAction;
		private global::Luminis.Its.Workbench.ModelComplexTypeConnectorConnectAction modelComplexTypeConnectorConnectAction;
		private global::Luminis.Its.Workbench.EntityRelationConnectorConnectAction entityRelationConnectorConnectAction;
		private global::Luminis.Its.Workbench.RelationEntityConnectorConnectAction relationEntityConnectorConnectAction;
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (activeView.SelectedToolboxItemSupportsFilterString(global::Luminis.Its.Workbench.WorkbenchToolboxHelper.CommentsReferenceTypesFilterString))
				{
					if (this.commentsReferenceTypesConnectAction == null)
					{
						this.commentsReferenceTypesConnectAction = new global::Luminis.Its.Workbench.CommentsReferenceTypesConnectAction(this);
						this.commentsReferenceTypesConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.commentsReferenceTypesConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::Luminis.Its.Workbench.WorkbenchToolboxHelper.ModelComplexTypeConnectorFilterString))
				{
					if (this.modelComplexTypeConnectorConnectAction == null)
					{
						this.modelComplexTypeConnectorConnectAction = new global::Luminis.Its.Workbench.ModelComplexTypeConnectorConnectAction(this);
						this.modelComplexTypeConnectorConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.modelComplexTypeConnectorConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::Luminis.Its.Workbench.WorkbenchToolboxHelper.EntityRelationConnectorFilterString))
				{
					if (this.entityRelationConnectorConnectAction == null)
					{
						this.entityRelationConnectorConnectAction = new global::Luminis.Its.Workbench.EntityRelationConnectorConnectAction(this);
						this.entityRelationConnectorConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.entityRelationConnectorConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::Luminis.Its.Workbench.WorkbenchToolboxHelper.RelationEntityConnectorFilterString))
				{
					if (this.relationEntityConnectorConnectAction == null)
					{
						this.relationEntityConnectorConnectAction = new global::Luminis.Its.Workbench.RelationEntityConnectorConnectAction(this);
						this.relationEntityConnectorConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relationEntityConnectorConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					pointArgs.DiagramClientView.ActiveMouseAction = action;
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				activeView.Toolbox.SelectedToolboxItemUsed();
			}
		}
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.commentsReferenceTypesConnectAction != null)
					{
						this.commentsReferenceTypesConnectAction.Dispose();
						this.commentsReferenceTypesConnectAction = null;
					}
					if(this.modelComplexTypeConnectorConnectAction != null)
					{
						this.modelComplexTypeConnectorConnectAction.Dispose();
						this.modelComplexTypeConnectorConnectAction = null;
					}
					if(this.entityRelationConnectorConnectAction != null)
					{
						this.entityRelationConnectorConnectAction.Dispose();
						this.entityRelationConnectorConnectAction = null;
					}
					if(this.relationEntityConnectorConnectAction != null)
					{
						this.relationEntityConnectorConnectAction.Dispose();
						this.relationEntityConnectorConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#endregion
		#region Constructors, domain class Id
	
		/// <summary>
		/// ClassDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xb3aa99e6, 0x38af, 0x404c, 0xb4, 0xdc, 0xe4, 0x11, 0xec, 0x7c, 0x8f, 0x0b);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ClassDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartition : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ClassDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Luminis.Its.Workbench
{
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelRelation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelComplexType), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelEntity), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.CaseFileRelation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.CaseFileEntity), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ObjectModelSpec), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.CaseFileModelSpec), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelTypeReferencesModelComplexTypes), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.CaseFileEntityReferencesChildCaseFileRelations), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.CaseFileRelationReferencesChildCaseFileEntity), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.EntityHasRelations), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.Comment), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.CommentReferencesSubjects), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.RelationHasEntity), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : DslModeling::AddRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (childElement.IsDeleted)
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::Luminis.Its.Workbench.ModelRelation)
				{
					parentElement = GetParentForModelRelation((global::Luminis.Its.Workbench.ModelRelation)childElement);
				} else
				if(childElement is global::Luminis.Its.Workbench.ModelComplexType)
				{
					parentElement = GetParentForModelComplexType((global::Luminis.Its.Workbench.ModelComplexType)childElement);
				} else
				if(childElement is global::Luminis.Its.Workbench.ModelEntity)
				{
					parentElement = GetParentForModelEntity((global::Luminis.Its.Workbench.ModelEntity)childElement);
				} else
				if(childElement is global::Luminis.Its.Workbench.CaseFileRelation)
				{
					parentElement = GetParentForCaseFileRelation((global::Luminis.Its.Workbench.CaseFileRelation)childElement);
				} else
				if(childElement is global::Luminis.Its.Workbench.CaseFileEntity)
				{
					parentElement = GetParentForCaseFileEntity((global::Luminis.Its.Workbench.CaseFileEntity)childElement);
				} else
				if(childElement is global::Luminis.Its.Workbench.ObjectModelSpec)
				{
					parentElement = GetParentForObjectModelSpec((global::Luminis.Its.Workbench.ObjectModelSpec)childElement);
				} else
				if(childElement is global::Luminis.Its.Workbench.CaseFileModelSpec)
				{
					parentElement = GetParentForCaseFileModelSpec((global::Luminis.Its.Workbench.CaseFileModelSpec)childElement);
				} else
				if(childElement is global::Luminis.Its.Workbench.Comment)
				{
					parentElement = GetParentForComment((global::Luminis.Its.Workbench.Comment)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::Luminis.Its.Workbench.ObjectModelSpec GetParentForModelEntity( global::Luminis.Its.Workbench.ModelType root )
			{
				// Segments 0 and 1
				global::Luminis.Its.Workbench.ObjectModelSpec result = root.ObjectModelSpec;
				if ( result == null ) return null;
				return result;
			}
			public static global::Luminis.Its.Workbench.ModelRoot GetParentForComment( global::Luminis.Its.Workbench.Comment root )
			{
				// Segments 0 and 1
				global::Luminis.Its.Workbench.ModelRoot result = root.ModelRoot;
				if ( result == null ) return null;
				return result;
			}
			public static global::Luminis.Its.Workbench.ModelRoot GetParentForObjectModelSpec( global::Luminis.Its.Workbench.ObjectModelSpec root )
			{
				// Segments 0 and 1
				global::Luminis.Its.Workbench.ModelRoot result = root.ModelRoot;
				if ( result == null ) return null;
				return result;
			}
			public static global::Luminis.Its.Workbench.ModelRoot GetParentForCaseFileModelSpec( global::Luminis.Its.Workbench.CaseFileModelSpec root )
			{
				// Segments 0 and 1
				global::Luminis.Its.Workbench.ModelRoot result = root.ModelRoot;
				if ( result == null ) return null;
				return result;
			}
			public static global::Luminis.Its.Workbench.CaseFileModelSpec GetParentForCaseFileRelation( global::Luminis.Its.Workbench.CaseFileType root )
			{
				// Segments 0 and 1
				global::Luminis.Its.Workbench.CaseFileModelSpec result = root.CaseFileModelSpec;
				if ( result == null ) return null;
				return result;
			}
			public static global::Luminis.Its.Workbench.CaseFileModelSpec GetParentForCaseFileEntity( global::Luminis.Its.Workbench.CaseFileType root )
			{
				// Segments 0 and 1
				global::Luminis.Its.Workbench.CaseFileModelSpec result = root.CaseFileModelSpec;
				if ( result == null ) return null;
				return result;
			}
			public static global::Luminis.Its.Workbench.ObjectModelSpec GetParentForModelRelation( global::Luminis.Its.Workbench.ModelType root )
			{
				// Segments 0 and 1
				global::Luminis.Its.Workbench.ObjectModelSpec result = root.ObjectModelSpec;
				if ( result == null ) return null;
				return result;
			}
			public static global::Luminis.Its.Workbench.ObjectModelSpec GetParentForModelComplexType( global::Luminis.Its.Workbench.ModelType root )
			{
				// Segments 0 and 1
				global::Luminis.Its.Workbench.ObjectModelSpec result = root.ObjectModelSpec;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::Luminis.Its.Workbench.ModelTypeHasAttributes)
				{
					global::System.Collections.IEnumerable elements = GetModelEntityForModelEntityShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelTypeHasAttributes)e.ModelElement);
					UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelEntityShape), "AttributesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Luminis.Its.Workbench.ModelTypeHasAttributes)
				{
					global::System.Collections.IEnumerable elements = GetModelRelationForModelRelationShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelTypeHasAttributes)e.ModelElement);
					UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelRelationShape), "AttributesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Luminis.Its.Workbench.ModelTypeHasAttributes)
				{
					global::System.Collections.IEnumerable elements = GetModelComplexTypeForModelComplexTypeShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelTypeHasAttributes)e.ModelElement);
					UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelComplexTypeShape), "AttributesCompartment", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetModelEntityForModelEntityShapeAttributesCompartmentFromLastLink(global::Luminis.Its.Workbench.ModelTypeHasAttributes root)
			{
				// Segment 0
				global::Luminis.Its.Workbench.ModelType result = root.ModelType;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelEntityForModelEntityShapeAttributesCompartment(global::Luminis.Its.Workbench.ModelAttribute root)
			{
				// Segments 1 and 0
				global::Luminis.Its.Workbench.ModelType result = root.ModelType;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelRelationForModelRelationShapeAttributesCompartmentFromLastLink(global::Luminis.Its.Workbench.ModelTypeHasAttributes root)
			{
				// Segment 0
				global::Luminis.Its.Workbench.ModelType result = root.ModelType;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelRelationForModelRelationShapeAttributesCompartment(global::Luminis.Its.Workbench.ModelAttribute root)
			{
				// Segments 1 and 0
				global::Luminis.Its.Workbench.ModelType result = root.ModelType;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelComplexTypeForModelComplexTypeShapeAttributesCompartmentFromLastLink(global::Luminis.Its.Workbench.ModelTypeHasAttributes root)
			{
				// Segment 0
				global::Luminis.Its.Workbench.ModelType result = root.ModelType;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelComplexTypeForModelComplexTypeShapeAttributesCompartment(global::Luminis.Its.Workbench.ModelAttribute root)
			{
				// Segments 1 and 0
				global::Luminis.Its.Workbench.ModelType result = root.ModelType;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::Luminis.Its.Workbench.ModelTypeHasAttributes)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetModelEntityForModelEntityShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelTypeHasAttributes)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelEntityShape), "AttributesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Luminis.Its.Workbench.ModelTypeHasAttributes)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetModelRelationForModelRelationShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelTypeHasAttributes)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelRelationShape), "AttributesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Luminis.Its.Workbench.ModelTypeHasAttributes)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetModelComplexTypeForModelComplexTypeShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelTypeHasAttributes)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelComplexTypeShape), "AttributesCompartment", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelAttribute), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::Luminis.Its.Workbench.ModelAttribute && e.DomainProperty.Id == global::Luminis.Its.Workbench.ModelAttribute.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelEntityForModelEntityShapeAttributesCompartment((global::Luminis.Its.Workbench.ModelAttribute)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelEntityShape), "AttributesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Luminis.Its.Workbench.ModelAttribute && e.DomainProperty.Id == global::Luminis.Its.Workbench.ModelAttribute.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelRelationForModelRelationShapeAttributesCompartment((global::Luminis.Its.Workbench.ModelAttribute)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelRelationShape), "AttributesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::Luminis.Its.Workbench.ModelAttribute && e.DomainProperty.Id == global::Luminis.Its.Workbench.ModelAttribute.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelComplexTypeForModelComplexTypeShapeAttributesCompartment((global::Luminis.Its.Workbench.ModelAttribute)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelComplexTypeShape), "AttributesCompartment", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetModelEntityForModelEntityShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelAttribute)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::Luminis.Its.Workbench.ModelEntityShape compartmentShape = pel as global::Luminis.Its.Workbench.ModelEntityShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelEntityForModelEntityShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelTypeHasAttributes)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelEntityShape), "AttributesCompartment", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelEntityForModelEntityShapeAttributesCompartment((global::Luminis.Its.Workbench.ModelAttribute)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelEntityShape), "AttributesCompartment", repaintOnly);
					}
				}
				if(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetModelRelationForModelRelationShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelAttribute)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::Luminis.Its.Workbench.ModelRelationShape compartmentShape = pel as global::Luminis.Its.Workbench.ModelRelationShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelRelationForModelRelationShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelTypeHasAttributes)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelRelationShape), "AttributesCompartment", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelRelationForModelRelationShapeAttributesCompartment((global::Luminis.Its.Workbench.ModelAttribute)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelRelationShape), "AttributesCompartment", repaintOnly);
					}
				}
				if(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetModelComplexTypeForModelComplexTypeShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelAttribute)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::Luminis.Its.Workbench.ModelComplexTypeShape compartmentShape = pel as global::Luminis.Its.Workbench.ModelComplexTypeShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelComplexTypeForModelComplexTypeShapeAttributesCompartmentFromLastLink((global::Luminis.Its.Workbench.ModelTypeHasAttributes)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelComplexTypeShape), "AttributesCompartment", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelComplexTypeForModelComplexTypeShapeAttributesCompartment((global::Luminis.Its.Workbench.ModelAttribute)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelComplexTypeShape), "AttributesCompartment", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelEntityForModelEntityShapeAttributesCompartment((global::Luminis.Its.Workbench.ModelAttribute)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelEntityShape), "AttributesCompartment", repaintOnly);
					}
				}
				if(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelRelationForModelRelationShapeAttributesCompartment((global::Luminis.Its.Workbench.ModelAttribute)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelRelationShape), "AttributesCompartment", repaintOnly);
					}
				}
				if(typeof(global::Luminis.Its.Workbench.ModelTypeHasAttributes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelComplexTypeForModelComplexTypeShapeAttributesCompartment((global::Luminis.Its.Workbench.ModelAttribute)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Luminis.Its.Workbench.ModelComplexTypeShape), "AttributesCompartment", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelTypeReferencesModelComplexTypes), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::Luminis.Its.Workbench.ModelTypeReferencesModelComplexTypes.ContainerNameDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::Luminis.Its.Workbench.ComplexTypeConnector.FindComplexTypeConnectorDecorator("Name");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Luminis.Its.Workbench.ModelTypeReferencesModelComplexTypes.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.CommentReferencesSubjects), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.RelationHasEntity), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.EntityHasRelations), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.ModelTypeReferencesModelComplexTypes), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.CaseFileEntityReferencesChildCaseFileRelations), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Luminis.Its.Workbench.CaseFileRelationReferencesChildCaseFileEntity), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::Luminis.Its.Workbench.ClassDiagram diagram = linkShape.Diagram as global::Luminis.Its.Workbench.ClassDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
