//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luminis.Its.Workbench.DslPackage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "its";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Its";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Luminis";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID WorkbenchDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(WorkbenchCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID WorkbenchExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(WorkbenchCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewWorkbenchExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(WorkbenchCommandSetId), 0x0001);
	
		// Package identifier
		public const string WorkbenchPackageId = "c9659392-bc30-455b-ab3b-9b3f64727a62";
		
		// Editor factory identifier
		public const string WorkbenchEditorFactoryId = "6016cee0-5bfc-40ee-ab9c-d16c9e7a682f";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string WorkbenchModelExplorerToolWindowId = "4e973415-dda5-445b-a27f-0b624f7d6cb0";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Luminis.Its.Workbench.DslPackage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string WorkbenchCommandSetId = "3ba4c1f3-86f0-4417-a5e4-a4501ed32953";
	}
}